target 'BitmovinYospaceModule_Example' do
    use_frameworks!
  platform :ios, '9.0'
  pod 'BitmovinYospaceModule', :path => '../'
  pod 'BitmovinPlayer', git: 'https://github.com/bitmovin/bitmovin-player-ios-sdk-cocoapod.git', tag: '2.13.0'
end
